-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 18, 2020 at 07:59 AM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.1.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `godconsciousness`
--

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `id` int(11) NOT NULL,
  `email` varchar(200) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`id`, `email`, `address`, `mobile`, `is_active`, `created_at`) VALUES
(1, 'godsconsciousnes@gmail.com', '73 Rama Lane, Talab Tillo, Jammu Tawi, Pin 180005', '+919419185085', 1, '2020-06-08 06:22:20');

-- --------------------------------------------------------

--
-- Table structure for table `images`
--

CREATE TABLE `images` (
  `id` int(11) NOT NULL,
  `module_id` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `image_name` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `images`
--

INSERT INTO `images` (`id`, `module_id`, `type`, `image_name`, `is_active`, `created_at`) VALUES
(1, 2, 'AboutWelcomeMessage', 'aunty-pics.jpg', 0, '2020-07-16 09:20:33'),
(2, 2, 'AboutWelcomeMessage', 'dsfdasf a_1594893070328.png', 0, '2020-07-16 09:51:10'),
(3, 2, 'AboutWelcomeMessage', 'dsfdasf a_1594893148658.png', 0, '2020-07-16 09:52:28'),
(4, 0, 'bannerHome', 'homeBannerAuntypic_1594893382185.jpg', 1, '2020-07-16 09:56:22'),
(5, 0, 'bannerHome', 'dsfdasf a_1594894515725.png', 0, '2020-07-16 10:15:15'),
(6, 0, 'bannerHome', 'dsfdasf_1594894835578.png', 0, '2020-07-16 10:20:35'),
(7, 0, 'bannerHome', 'dsfdasf_1594895033110.png', 0, '2020-07-16 10:23:53'),
(8, 3, 'Prayer', 'DailtPrayers_1594895265670.png', 1, '2020-07-16 10:27:45'),
(9, 4, 'Prayer', 'DailtPrayers_1594895358060.png', 1, '2020-07-16 10:29:18'),
(10, 5, 'Miracle', 'believe_1594896909207.jpeg', 1, '2020-07-16 10:55:09'),
(11, 6, 'Miracle', 'dine_1594896977438.jpg', 0, '2020-07-16 10:56:17'),
(12, 7, 'Miracle', 'baby_1594897036073.jpg', 1, '2020-07-16 10:57:16'),
(13, 6, 'Miracle', 'pic3_1594897396407.jpg', 0, '2020-07-16 11:03:16'),
(14, 9, 'Event', 'pic3_1594901670827.jpg', 1, '2020-07-16 12:14:30'),
(15, 10, 'Event', 'baby_1594904649523.jpg', 1, '2020-07-16 13:04:09'),
(16, 0, 'bannerHome', 'baby_1594904816333.jpg', 0, '2020-07-16 13:06:56'),
(17, 11, 'Prayer', 'homeBannerAuntypic_1594904890993.jpg', 1, '2020-07-16 13:08:11'),
(18, 2, 'AboutWelcomeMessage', 'homeBannerAuntypic_1594904949975.jpg', 1, '2020-07-16 13:09:09'),
(19, 6, 'Miracle', 'dsfdasf_1594905012832.png', 0, '2020-07-16 13:10:12'),
(20, 6, 'Miracle', 'pic3_1594905042724.jpg', 1, '2020-07-16 13:10:42'),
(21, 12, 'Miracle', 'dine_1594905092661.jpg', 1, '2020-07-16 13:11:32'),
(22, 0, 'bannerAbout', 'auntyji_1594906839622.jpg', 1, '2020-07-16 13:40:39'),
(23, 0, 'bannerContact', 'contact_1594963093489.jpeg', 1, '2020-07-17 05:18:13'),
(24, 0, 'bannerMiracle', 'miracle_1594984180195.jpeg', 1, '2020-07-17 11:09:40'),
(25, 0, 'bannerDirection', 'abc-accomplished-alphabet-48898_1594989291162.jpg', 1, '2020-07-17 12:34:51'),
(26, 41, 'Direction', 'img_1_1594989354397.jpg', 1, '2020-07-17 12:35:54'),
(27, 42, 'Direction', 'img_2_1594989393322.jpg', 1, '2020-07-17 12:36:33'),
(28, 43, 'Direction', 'img_3_1594989418768.jpg', 1, '2020-07-17 12:36:58'),
(29, 0, 'bannerOBE', 'obe_banner_resized_1594990284455.jpg', 1, '2020-07-17 12:51:24'),
(30, 1, 'OBE', 'about_3_1594990700191.jpg', 1, '2020-07-17 12:58:20'),
(31, 0, 'bannerBlog', 'blog.jpg', 1, '2020-07-17 12:34:51'),
(32, 0, 'bannerBlog', 'adult-advice-analysis-1050297_1594992168218.jpg', 0, '2020-07-17 13:22:48'),
(33, 44, 'Event', 'amplifier-artist-audio-114820_1595050342624.jpg', 1, '2020-07-18 05:32:22'),
(34, 0, 'bannerEvent', 'leader_1595050439809.jpg', 1, '2020-07-18 05:33:59');

-- --------------------------------------------------------

--
-- Table structure for table `links`
--

CREATE TABLE `links` (
  `id` int(11) NOT NULL,
  `module_id` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `website_link` varchar(1024) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `links`
--

INSERT INTO `links` (`id`, `module_id`, `type`, `website_link`, `is_active`, `created_at`) VALUES
(1, 1, 'OBE', 'https://i.ytimg.com/vi/O_u4TV5Typs/sddefault.jpg', 1, '2020-07-12 09:54:09'),
(2, 2, 'AboutWelcomeMessage', 'https://vimeo.com/45830194', 0, '2020-07-12 09:54:09'),
(3, 2, 'AboutWelcomeMessage', 'http://godsconsciousness.com/obe', 1, '2020-07-16 09:52:56'),
(4, 3, 'Prayer', 'http://godsconsciousness.com/prayer?month=7&day=10', 1, '2020-07-16 10:27:45'),
(5, 0, 'socialFacebook', 'https://www.facebook.com/groups/429971720508946/', 1, '2020-07-16 11:24:23'),
(6, 0, 'socialInstagram', 'https://www.instagram.com/godsconsciousness_gc', 1, '2020-07-16 11:24:23'),
(7, 0, 'socialYoutube', 'https://www.youtube.com/channel/UCKeVsVRweYnZFBEZUSsE47A', 1, '2020-07-16 11:24:23'),
(8, 0, 'mapLink', 'https://maps.google.com/maps?q=73%20Rama%20Lane%2C%20Talab%20Tillo%2C%20Jammu%20Tawi%2C%20Pin%20180005%20&t=&z=13&ie=UTF8&iwloc=&output=embed', 1, '2020-07-16 11:24:23'),
(9, 44, 'Event', 'https://www.google.com/', 1, '2020-07-18 05:32:22');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` blob,
  `token` varchar(255) DEFAULT NULL,
  `account_id` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `name`, `username`, `password`, `token`, `account_id`, `is_active`, `created_at`) VALUES
(1, 'Kamlesh', 'root', 0x41579e3d233189c2e2c3af45c10c96c5, 'eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ', 'IiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik', 1, '2020-03-03 09:32:09');

-- --------------------------------------------------------

--
-- Table structure for table `website_content`
--

CREATE TABLE `website_content` (
  `id` int(11) NOT NULL,
  `type` varchar(100) DEFAULT NULL,
  `title` text,
  `content` text,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `location` text,
  `contact` varchar(100) DEFAULT NULL,
  `is_active` tinyint(4) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `website_content`
--

INSERT INTO `website_content` (`id`, `type`, `title`, `content`, `date`, `time`, `location`, `contact`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'OBE', '', 'Dear AllSharing my Out of Body Experience. I would like to share something peculiar. It has been 10 days and every night I seem to be getting similar visions. I see myself on the surface of a sea, standing without any support. There I notice a figure that seems to be 3 in 1.  The first figure is a very tall person who is dressed as a saint, has peculiarly long feet and fair skin, who I now recollect to have seen a couple of times. Second is my maternal Grandmother (Naani). The  Third is someone who I recall to be tall and thin with grey eyes. From 3 THEY merge into ONE. And now My Nani starts talking to me. SHE says, “Just look at the amount of ABUNDANCE that is here. It belongs to you. Take your share and go. Come, bring your buckets and fill it.”I pick up a bucket next to me and bend down to fill it with sea water- my share of abundance. As I look into the bucket, expecting water to collect in it, I notice something very different. It was being filled with STARS instead. There was one thing SHE kept repeating, “Take YOUR share. Don’t get swayed by what is in other’s bucket. There is ENOUGH for each one in this UNIVERSE. WE have  ample to give you all individually. Come and take your own!”SHE went on to explain, “What do WE mean by ‘Another’s bucket ’? It means, don’t see what others have and thereby want it for yourself just because they have it. If others have a better life, don’t resort to jealousy and crave theirs. Dont  say that you want what they have. DESIRE, Want, Ask anything, everything that you need because you feel for it. You really really want it for yourself... it could be more money, better relationships, good health, a better job, children having a great life, travel, jewels, clothes, food ..... anything!!!FOCUS on what You WANT and WHAT makes You HAPPY. DO NOT FEEL SAD. Don’t Ask out of ANXIETY, FEAR, LACK, PAUCITY.. FEEL GOOD and ASK.  THE  INTENT behind your Want or Desire -must be KIND, GOOD and RIGHT . Take your share of HAPPINESS; we have STARS for you too.”', '0000-00-00', '14:00:00', NULL, NULL, 1, '2020-07-12 13:20:07', '2020-07-12 13:20:07'),
(2, 'AboutWelcomeMessage', '', 'Gods Consciousness is a community initiated by Ms. Dimple Anil (a Clairvoyant Psychic Medium,\nan educationist for more than three decades) who receives MESSAGES in the form of PRAYERS, GUIDELINES\n& DIRECTIONS from our Loved Ones who have crossed over - Our GUARDIAN ANGELS. These Prayers and Directions are simple, pragmatic and extremely powerful and help us receive, manifest Happiness, love, great health, wealth, fame, safety, security, great relationships, proficiency in their talent or skills, prosperity, amazing academic, sports or professional growth, relief from legal battles, awards and accolades, spiritual growth and ascension of your spirit, wisdom.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-12 13:20:07', '2020-07-12 13:20:07'),
(3, 'Prayer', 'My Lord, My Master...', 'My Lord\nMy Master\nEnvelope me and my Family in Complete Well Being Now\nThank You My Lord\nThank You My Master', '2020-07-16', NULL, NULL, NULL, 1, '2020-07-16 10:27:45', '2020-07-16 10:27:45'),
(4, 'Prayer', 'Dear Co-travellers...', 'Dear Co-travellers\nToday\nWith utmost Consciousness we all will do Prayers of Forgiveness.', '2020-07-15', NULL, NULL, NULL, 1, '2020-07-16 10:29:18', '2020-07-16 10:29:18'),
(5, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\nThank you Dimple MA.\nLove you.\nI wanted a clean, spacious home.\nI have.\nI wanted to wear sarees to my workplace.\nI have started.\nI wanted loads of plants in my home.\nI have\nI wanted enough resources for the education of my children and their marriages.\nBoth married and settled.\nI wanted to be Naani Daadi.\nI am both\nI wanted my son and daughter in law to have good relationship.\nThey have.\nI wanted my children to travel.\nThey do.\nI wanted good health for my husband and myself.\nWe are healthy.\nBow, Namaskar, love, respect, regards to you Dimple Ma.\nJeenay ka mazaa\nJeenay ka tareeka\nSab Aapnay dey diya\nThank you\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(6, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\nThank you Di for the prayers.\nI was sowing ego and one up-manship and reaping migraine.\nThank you for this awakening.\n\nDimple Anil: All Gratitude to THEM, dear.\nTreat reading your Sharing.\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(7, 'Miracle', 'I conceived after four years of marriage', 'Please share\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\nThen miscarriage,\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\nSow bad, receive badder, says Auntyji, friends I am living this.\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\nThank you dear Aunty ji for making me the Creator of my life.\n???? Bow Bow Bow Bow to you.\n\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(8, 'AboutFooterMessage', '', 'Prayers are SIMPLE and DOABLE and have all those lead a more peaceful, successful, glorious, magnificent, healthy, prosperous and abundant life...', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-12 13:20:07', '2020-07-12 13:20:07'),
(9, 'Event', 'Annivercery Cel', 'abcdd', '2020-07-23', NULL, NULL, NULL, 1, '2020-07-16 12:14:30', '2020-07-16 12:14:30'),
(10, 'Event', 'New Meditation Speech by Dr. anil Dimple ', 'New Meditation Speech by Dr. anil Dimple please come ', '2020-07-31', NULL, NULL, NULL, 1, '2020-07-16 13:04:09', '2020-07-16 13:04:09'),
(11, 'Prayer', 'Meray Bhagwan ji, Meray Khuda ji', 'Meray Bhagwan ji\nMeray Khuda ji\nMy Lord\nNOW hold me and take me to places, people and things that will make me Laugh, Happy and Prosperous.\nThank You Meray Bhagwan ji\nThank You Meray Khuda ji\nThank You My Lord.', '2020-07-14', NULL, NULL, NULL, 1, '2020-07-16 13:08:10', '2020-07-16 13:08:10'),
(12, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\n\nLast night my husband was very sad and tensed.\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\n\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\nThen I see him getting ready.\nAs we both were about to leave, he told me that he didn’t have money.\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\n\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\nI went in. My husband and others followed me.\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\n\nEveryone including my husband was zapped,\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\n\nWe had a BLAST!\n\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\n\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\n\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\n\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\n\nThank you Divine\nThank you Neetu maa\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(13, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(14, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(15, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(16, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(17, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(18, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(19, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(20, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(21, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(22, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(23, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(24, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(25, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(26, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(27, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(28, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(29, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(30, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(31, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(32, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(33, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(34, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17');
INSERT INTO `website_content` (`id`, `type`, `title`, `content`, `date`, `time`, `location`, `contact`, `is_active`, `created_at`, `updated_at`) VALUES
(35, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(36, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(37, 'Miracle', 'My manifestations after coming in Prayers...', 'Life seems to be sorted fully.\r\nThank you Dimple MA.\r\nLove you.\r\nI wanted a clean, spacious home.\r\nI have.\r\nI wanted to wear sarees to my workplace.\r\nI have started.\r\nI wanted loads of plants in my home.\r\nI have\r\nI wanted enough resources for the education of my children and their marriages.\r\nBoth married and settled.\r\nI wanted to be Naani Daadi.\r\nI am both\r\nI wanted my son and daughter in law to have good relationship.\r\nThey have.\r\nI wanted my children to travel.\r\nThey do.\r\nI wanted good health for my husband and myself.\r\nWe are healthy.\r\nBow, Namaskar, love, respect, regards to you Dimple Ma.\r\nJeenay ka mazaa\r\nJeenay ka tareeka\r\nSab Aapnay dey diya\r\nThank you\r\nThank you', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:55:09', '2020-07-16 10:55:09'),
(38, 'Miracle', 'I come from and got married into a joint family.', 'I come from a joint family and got married into a joint family. In my new family, I saw that each one loved to play politics with one another. Saying bad behind someone\'s back and be sweet in front of them, I couldn\'t cope with all this and started getting migraines. I always felt I was clear and doing what was right for me!\r\nAfter coming into prayers I realised, that my claim of being clear-hearted was filled with ego and feeling of superiority. I became aware of my thoughts and my knowledge of my own self eventually healed my migraine.\r\nThank you Di for the prayers.\r\nI was sowing ego and one up-manship and reaping migraine.\r\nThank you for this awakening.\r\n\r\nDimple Anil: All Gratitude to THEM, dear.\r\nTreat reading your Sharing.\r\nYour fine tuning with THE DIVINE and understanding of THEIR ways is remarkable.\r\nBow to THEM.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:56:17', '2020-07-16 10:56:17'),
(39, 'Miracle', 'I conceived after four years of marriage', 'Please share\r\nI conceived after four years of marriage, loads and loads of efforts. I was happy but insecure and very anxious. Was sowing mixed bag of emotions.\r\nInsecurities and anxieties out did happiness. I would thank profusely for this conception but at the same time constantly sowed anxiety, fear, doubt, insecurity.\r\nThen miscarriage,\r\nMy world fell apart but it was an amazingly enriching experience. I knew what wrong I had sown. Strange confidence came in me to sow more and more of goodies, good feelings. This miscarriage is my teacher. I understood what Dimple Auntyji says. I knew where I was wrong, what I had sown I started meditations.\r\nI started shifting my focus. I started feeling better. This my miscarriage is my teacher, it helped me in all my living. Didn\'t conceive for next three years, but working on myself continued.\r\nJust day before my pregnancy is confirmed. I am at a much better place today. I know this baby will be born healthy and happy. I am so sure. Thank you Dimple Auntyji. Journey of knowing what we want and what we sow. I get results of my sowing instantly.\r\nI sow low feel for whatever reason, I get more of it and it comes from anywhere. I sow good feelings and I get the same from anywhere.\r\nSow bad, receive badder, says Auntyji, friends I am living this.\r\nPlease be alert. I am a living example. I sowed thank you, happiness and anxiety in first conception. Anxiety was more and miscarriage happened, now happiness and gratitude is more and I know I have in my womb healthy and happy Soul. I am confident.\r\nAnxiety when it comes, instead of letting it multiply, I wash my face, put on music, start meditation, go for a walk. All directions of Auntyji I follow to the T.\r\nThank you dear Aunty ji for making me the Creator of my life.\r\n???? Bow Bow Bow Bow to you.\r\n\r\nDimple Anil: Your learning through a rough process shows how Blessed you are dear. Divine Wisdom, your Trust and Faith is immense. Anyone would have buckled.\r\nNot easy, not at all from where you started and where your realization has brought you today is worth emulating. My happiness for you is gushing out, infact I am smiling with teary eyes. You truly are an example of being a Creator of your destiny. Thank you so much dear for your sharing.\r\nAll Blessings dear. THEY have no option but to shower and keep on showering Blessings.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 10:57:16', '2020-07-16 10:57:16'),
(40, 'Miracle', 'Dine & Dance', 'Drink Dine & Dance\r\n\r\nLast night my husband was very sad and tensed.\r\nWe had plans of going for Drinks, Dance & Dinner yesterday but since he was so tensed he came back & refused. “Tina not today. Let’s just go to the temple.No party on my mind. I am not at ease.”, he said.\r\n\r\nI agreed and pointed at Neetu maa\'s pic to him, “Look at HER ! Tell HER your worries & things will be fine. He went off to sleep at 8 when he woke up at 9 pm, he saw me all ready and decked up. “Where are you going?,” he asked.\r\nI replied, “This is the last Saturday of 2019 so you relax I\'m going to celebrate alone.”\r\nThen I see him getting ready.\r\nAs we both were about to leave, he told me that he didn’t have money.\r\nI quipped, “ Well, that’s a smart way of asking me ????!” I kept around ₹5k but I knew that bills at such pubs go beyond ₹8kto 9k\r\nI left with my husband, my brother in law and 2 more friends. When we reached our destination we got to know that one of the biggest chains of Delhi named Lord of the Drinks has opened in Lucknow and that night was its inaugural party where entry was strictly through invitation.\r\n\r\nI politely asked the bouncer outside the gate, “Can I just go in and have a look around? “ pleasantly he said, “YES.”\r\nI went in. My husband and others followed me.\r\nThen to our surprise drinks were offered, music dance, masti.! We stayed there till 1.00 am, till it all got over.\r\n\r\nEveryone including my husband was zapped,\r\nMy brother in law in utter disbelief kept chanting “Ye kya tha ? What was this? Free entry and free drinks worth over ₹ 11 k and No bill??? How and why did we we were get treated like privileged important guests???? “\r\n\r\nWe had a BLAST!\r\n\r\nI said, “This was a Divine Party gifted by the Angels. Before leaving the house I told Neetu maa, I have ₹5k rest is up to you.”\r\nSee what SHE & THEY weaved for not only ne but my companions.... man.. VVIP TREATMENT, MUSIC, DANCE, FREE DRINKS ... a truly MIRACULOUS MAGICAL NIGHT.”\r\n\r\nThey all are still in Shock!!!! and I more empowered and ever more grateful to THEM for raising my FAITH in THEM, THE DIVINE, ANGELS, GOD to this level. I am so proud of my faith in THEM. THEY give beyond our expectations and how!!!!\r\n\r\nWOW is my new mantra. I am in tears while sharing this with u all. It was so MAGICAL.\r\n\r\nNOT a penny spent and extravagant extraordinary magical fun filled evening was gifted by the Divine.\r\n\r\nThank you Divine\r\nThank you Neetu maa\r\nThank you for everything ????????????????????????', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-16 13:11:32', '2020-07-16 13:11:32'),
(41, 'Direction', 'William Shakespeare', 'O Lord that lends me life, lend me a heart replete with thankfulness.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-17 12:35:54', '2020-07-17 12:35:54'),
(42, 'Direction', 'Robert Louis Stevenson', 'Keep your eyes open to your mercies. The man who forgets to be thankful has fallen asleep in life.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-17 12:36:33', '2020-07-17 12:36:33'),
(43, 'Direction', 'Jefferson Bethke', 'Thankfulness is the quickest path to joy.', '0000-00-00', NULL, NULL, NULL, 1, '2020-07-17 12:36:58', '2020-07-17 12:36:58'),
(44, 'Event', 'Remember to old memories', 'abcdefghijklmnopqrstuvwxyz', '2020-07-20', '14:30:00', 'jaipur', '01254214582, 9254511544', 1, '2020-07-18 05:32:22', '2020-07-18 05:32:22');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `links`
--
ALTER TABLE `links`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `website_content`
--
ALTER TABLE `website_content`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `images`
--
ALTER TABLE `images`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- AUTO_INCREMENT for table `links`
--
ALTER TABLE `links`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `website_content`
--
ALTER TABLE `website_content`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
